### ISSUE TITLE
 Cannot call method 'say' of undefined

### ISSUE THREAD

**Issue by parthasharathi** [junosuarez/node-flite#1]
when i run the following program.
var flite = require('flite')

var message = "you know what we need? some more waffles!"

flite(function (err, speech) {
  speech.say(message, function (err) {
    if (err) console.error('I\'m afraid I can\'t do that, Dave', err);
  });
});
i getting  Cannot call method 'say' of undefined ERROR

**Comment by junosuarez** [comment]
try logging the error when you first call flite. this module requires several binaries to already be installed on your system, as indicated in the readme.

``` js
var flite = require('flite')

var message = "you know what we need? some more waffles!"

flite(function (err, speech) {
  if (err) { return console.error(err) }
  speech.say(message, function (err) {
    if (err) console.error('I\'m afraid I can\'t do that, Dave', err);
  });
});
```
